language: generic
sudo: required

services:
  - docker

notifications:
  on_success: never
  on_failure: always

before_install:
  - sudo apt-get -y install curl

script:
  - docker build -t pe46dro/xbackbone-docker ./src/
  - docker run -p 80:80 -d -e URL=http:\/\/127.0.0.1 --name xbackbone pe46dro/xbackbone-docker
  - curl --silent --show-error --fail http://127.0.0.1/login
